android_binary(
  name = "android",
  custom_package = "com.sys1yagi.project_generated_by_android_studio",
  srcs = glob(["src/main/java/com/sys1yagi/project_generated_by_android_studio/*.java"]),
  manifest = "src/main/AndroidManifest.xml",
  resource_files = glob(["src/main/res/**"]),
  deps = ["//external:android/appcompat_v4", "//external:android/appcompat_v7"],
)
